In [22]:
import cv2
import numpy as np
from keras.models import load_model
from keras.preprocessing import image
import tensorflow as tf
import matplotlib.pyplot as plt
# import required libraries
import sounddevice as sd
from scipy.io.wavfile import write
import wavio as wv
import os 
import shutil
import librosa

In [23]:
model = tf.keras.models.load_model('model4.h5')
speech_model = tf.keras.models.load_model("speech_model.h5")

In [24]:
final_results={1:'mask',0:'without mask'}
GR_dict={1:(0,255,0),0:(0,0,255)}

In [25]:
dict = {0:'Fear',1:'Happiness',2:'Sadness',3:'Neutral'}
dict1 = {0:'happy',1:'Happiness',2:'Neutral',3:'Sadness'}
# a=model.predict(X_test[i].reshape(1,48,48,1))
# print("Predicted:",dict[np.argmax(a)]," Actual:",dict[np.argmax(y_test[i])])

In [26]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [27]:
def extract_mfcc(filename):
    y, sr = librosa.load(filename, duration=3, offset=0.5)
    mfcc = np.mean(librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40).T, axis=0)
    return mfcc

In [28]:
cap = cv2.VideoCapture(0)

while True:
    try:
        shutil.rmtree('songs')
    except:
        print("unable to delete previous audio data or no song folder is present")
        
    count = 0
    ret, img = cap.read()
    print(ret)
#     gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img,1.05,5)
    
    for x,y,w,h in faces:
        
        face_img = img[y:y+h,x:x+w ]
#         resized = np.array(face_img,target_size=(128,128))
        resized = cv2.resize(face_img,(48,48))
        resized = np.array(tf.image.rgb_to_grayscale(resized,name = None)/255)
        reshaped=resized.reshape(1, 48, 48, 1)
        result = model.predict(reshaped)
        a = dict[np.argmax(result)]
        print(result)
        # a=model.predict(X_test[i].reshape(1,48,48,1))
        # print("Predicted:",dict[np.argmax(a)]," Actual:",dict[np.argmax(y_test[i])])
        
#         label = np.argmax(result,axis=1)[0]
        
        cv2.rectangle(img,(x,y),(x+w,y+h),GR_dict[1],2)
        cv2.rectangle(img,(x,y-40),(x+w,y),GR_dict[1],-1)
        cv2.putText(img, a, (x, y-10),cv2.FONT_HERSHEY_SIMPLEX,0.8,(255,255,255),2)
        
        # Sampling frequency
        freq = 44100

        # Recording duration
        duration = 1

        # Start recorder with the given values 
        # of duration and sample frequency
        recording = sd.rec(int(duration * freq), 
                           samplerate=freq, channels=1)

        # Record audio for the given number of seconds
        sd.wait()

        # This will convert the NumPy array to an audio
        # file with the given sampling frequency
        # write("recording0.wav", freq, recording)
            
        try:
            os.mkdir("songs")
        except:
            print("directry is already present")

        # Convert the NumPy array to audio file
        filename = "songs/recording"+str(count)+".wav"
        wv.write(filename, recording, freq, sampwidth=2)
        
        feature = extract_mfcc(filename)
        
        feature = np.array([feature])
        feature = feature.reshape(1, 40, 1)
        
        audio_result = speech_model.predict(feature)
        audio_result = np.argmax(audio_result)
        audio_result = dict1[audio_result]
        print(audio_result)
        
        count += 1
        
        cv2.putText(img, audio_result, (50,50),cv2.FONT_HERSHEY_SIMPLEX,0.8,(0,0,0))
            
    cv2.imshow('LIVE', img)
    key = cv2.waitKey(1)
    
    if key == 27: 
        break
        
cap.release()
cv2.destroyAllWindows()

True
[[0.00274134 0.88296807 0.04049175 0.07379895]]
happy
True
[[0.01379409 0.7265489  0.1895593  0.0700977 ]]
happy
True
[[0.02425578 0.37453735 0.24747835 0.35372856]]
happy
True
[[0.01704395 0.07727098 0.11791659 0.7877685 ]]
happy
True
[[0.01984727 0.01877535 0.11563686 0.84574056]]
happy
True
[[0.0167596  0.05500131 0.14359286 0.7846462 ]]
happy
True
[[0.44122946 0.01772739 0.44116154 0.09988157]]
happy
[[0.19977869 0.12807931 0.6046772  0.06746472]]
directry is already present
happy
True
[[0.0383913  0.18111685 0.25097    0.5295219 ]]
happy
True
[[0.48788905 0.01318327 0.394042   0.10488568]]
happy
[[0.05001317 0.16743493 0.67315626 0.10939571]]
directry is already present
happy
True
[[0.00358072 0.50378776 0.11475446 0.37787712]]
happy
True
[[0.5154051  0.00112256 0.39671403 0.08675834]]
happy
[[0.14299358 0.28676215 0.4922078  0.07803644]]
directry is already present
happy
True
[[0.40344593 0.00160718 0.42292047 0.17202637]]
happy
[[0.03818451 0.01399413 0.30408877 0.6437326 ]

True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
u

happy
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
[[0.01784913 0.08816475 0.8433499  0.05063625]]
happy
True
[[0.03185279 0.16014014 0.68190646 0.12610064]]
happy
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete pr

unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable

True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
u

happy
True
[[0.36285526 0.03665243 0.1446775  0.45581493]]
happy
True
[[0.11466386 0.11600637 0.607969   0.16136071]]
happy
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
unable to delete previous audio data or no song folder is present
True
[[0.63930386 0.009947   0.29678896 0.05396014]]
happy
True
[[0.20325233 0.04308934 0.13771461 0.6159437 ]]
happy
True
[[0.01115475 0.02611124 0.12332238 0.8394116 ]]
happy
True
[[0.1734815  0.00238795 0.17682329 0.6473073 ]]
happy
True
[[0.01360348 0.00389985 0.06443162 0.918065  ]]
happy
True
[[0.18324335 0.00192996 0.18566023 0.6291664 ]]
happy
True
[[0.257647   0.00154